modLoader = "javafml" #mandatory
loaderVersion = "[2,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GPLv3"
issueTrackerURL = "https://github.com/khjxiaogu/Convivium/issues"
[[mods]] #mandatory
modId = "convivium" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Convivium" #mandatory
authors = "khjxiaogu, Lyuuke"
logoFile="convivium.png"
description = '''
Build a party with this mod
'''
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
[[mixins]]
config="convivium.mixins.json"
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.convivium]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[26.1.2,)" #mandatory
    ordering="AFTER"
    side="BOTH"
# Here's another dependency
[[dependencies.convivium]]
    modId="minecraft"
    type="required"
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[26.1.2,26.2)"
    ordering="NONE"
    side="BOTH"
[[dependencies.convivium]]
    modId="caupona"
    type="required"
    # This version range declares a minimum of the current version up to but not including the next major version
    versionRange="[6.0.2,)"
    ordering="NONE"
    side="BOTH"